package hibernate.entity;
// Generated Jun 23, 2020 7:33:36 PM by Hibernate Tools 4.3.1



/**
 * Akun generated by hbm2java
 */
public class Akun  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private String state;

    public Akun() {
    }

    public Akun(int id, String username, String password, String state) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.state = state;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


