package hibernate.entity;
// Generated Jun 23, 2020 7:33:36 PM by Hibernate Tools 4.3.1



/**
 * Pengajuan generated by hbm2java
 */
public class Pengajuan  implements java.io.Serializable {


     private int id;
     private String nama;
     private String alamat;
     private String tujuan;
     private String waktu;
     private String keterangan;
     private String status;

    public Pengajuan() {
    }

    public Pengajuan(int id, String nama, String alamat, String tujuan, String waktu, String keterangan, String status) {
       this.id = id;
       this.nama = nama;
       this.alamat = alamat;
       this.tujuan = tujuan;
       this.waktu = waktu;
       this.keterangan = keterangan;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    
    public String getTujuan() {
        return this.alamat;
    }
    
    public void setTujuan(String tujuan) {
        this.alamat = alamat;
    }
    
    public String getWaktu() {
        return this.waktu;
    }
    
    public void setWaktu(String waktu) {
        this.waktu = waktu;
    }
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }


}


